import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
import psutil
import collections

datafsignal_x_axise = pd.read_csv('./sample.csv')                # reading csv file from the same directory
signal_x_axis = list((datafsignal_x_axise.iloc[:,0]).to_numpy()) # creating a list of the x axis
signal_y_axis = list((datafsignal_x_axise.iloc[:,1]).to_numpy()) # creating a list of the y axis

# function to update the data
# i is a counter which stats with 0, I think it's generated by FuncAnimation
def my_function(i):

    # appending the new data to plot them "I think the data would be automatically appended in the dataframe" 
    # I tried to change the csv but it doesn't allow me to save while the code is running and that's a problem
    signal_y_axis.append(i*20)
    # signal_x_axis.append(i+10)

    # clear axis "Try to comment this line and watch the difference you would know its importance"
    ax.cla()

    # plot signal_y_axis, I tried to plot singal_x_axis but it doesn't work properly 
    ax.plot(signal_y_axis)  
    ax.scatter(len(signal_y_axis)-1, signal_y_axis[-1]) # draws the point shown in the graph 

# define and adjust figure
fig = plt.figure(figsize=(12,6), facecolor='#DEDEDE')
ax  = plt.subplot(121)

# animate
ani = FuncAnimation(fig, my_function, interval=1000)
plt.show()
